// proto/recorder.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/recorder.proto

package recorderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_VIDEO_AU  Kind = 0
	Kind_USER_PCM  Kind = 1
	Kind_AGENT_PCM Kind = 2
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "VIDEO_AU",
		1: "USER_PCM",
		2: "AGENT_PCM",
	}
	Kind_value = map[string]int32{
		"VIDEO_AU":  0,
		"USER_PCM":  1,
		"AGENT_PCM": 2,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_recorder_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_proto_recorder_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_proto_recorder_proto_rawDescGZIP(), []int{0}
}

type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Kind          Kind                   `protobuf:"varint,2,opt,name=kind,proto3,enum=recorder.Kind" json:"kind,omitempty"`
	TsUs          uint64                 `protobuf:"varint,3,opt,name=ts_us,json=tsUs,proto3" json:"ts_us,omitempty"` // monotonic microseconds since this stream's first frame
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`              // VIDEO_AU: one H264 access unit (Annex-B). *_PCM: s16le mono 48kHz
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_proto_recorder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recorder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_proto_recorder_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Frame) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_VIDEO_AU
}

func (x *Frame) GetTsUs() uint64 {
	if x != nil {
		return x.TsUs
	}
	return 0
}

func (x *Frame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frames        uint64                 `protobuf:"varint,1,opt,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_recorder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recorder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_recorder_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetFrames() uint64 {
	if x != nil {
		return x.Frames
	}
	return 0
}

var File_proto_recorder_proto protoreflect.FileDescriptor

const file_proto_recorder_proto_rawDesc = "" +
	"\n" +
	"\x14proto/recorder.proto\x12\brecorder\"s\n" +
	"\x05Frame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\"\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x0e.recorder.KindR\x04kind\x12\x13\n" +
	"\x05ts_us\x18\x03 \x01(\x04R\x04tsUs\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x1d\n" +
	"\x03Ack\x12\x16\n" +
	"\x06frames\x18\x01 \x01(\x04R\x06frames*1\n" +
	"\x04Kind\x12\f\n" +
	"\bVIDEO_AU\x10\x00\x12\f\n" +
	"\bUSER_PCM\x10\x01\x12\r\n" +
	"\tAGENT_PCM\x10\x022<\n" +
	"\bRecorder\x120\n" +
	"\fRecordStream\x12\x0f.recorder.Frame\x1a\r.recorder.Ack(\x01B\x1fZ\x1dkyc/proto/recorder;recorderpbb\x06proto3"

var (
	file_proto_recorder_proto_rawDescOnce sync.Once
	file_proto_recorder_proto_rawDescData []byte
)

func file_proto_recorder_proto_rawDescGZIP() []byte {
	file_proto_recorder_proto_rawDescOnce.Do(func() {
		file_proto_recorder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recorder_proto_rawDesc), len(file_proto_recorder_proto_rawDesc)))
	})
	return file_proto_recorder_proto_rawDescData
}

var file_proto_recorder_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_recorder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_recorder_proto_goTypes = []any{
	(Kind)(0),     // 0: recorder.Kind
	(*Frame)(nil), // 1: recorder.Frame
	(*Ack)(nil),   // 2: recorder.Ack
}
var file_proto_recorder_proto_depIdxs = []int32{
	0, // 0: recorder.Frame.kind:type_name -> recorder.Kind
	1, // 1: recorder.Recorder.RecordStream:input_type -> recorder.Frame
	2, // 2: recorder.Recorder.RecordStream:output_type -> recorder.Ack
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_recorder_proto_init() }
func file_proto_recorder_proto_init() {
	if File_proto_recorder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recorder_proto_rawDesc), len(file_proto_recorder_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recorder_proto_goTypes,
		DependencyIndexes: file_proto_recorder_proto_depIdxs,
		EnumInfos:         file_proto_recorder_proto_enumTypes,
		MessageInfos:      file_proto_recorder_proto_msgTypes,
	}.Build()
	File_proto_recorder_proto = out.File
	file_proto_recorder_proto_goTypes = nil
	file_proto_recorder_proto_depIdxs = nil
}
